### ISSUE TITLE
nice-to-have: bitte die Schriftfarbe ändern

### ISSUE THREAD

**Issue by HappyPony** [jw23578/IchBinDa#2]
ich bin auch mit dem langweiligen weiß oder mit gellem Gelb auf schwarzem Hintergrund einverstanden. Das jetzige pink auf dem schwarzen bzw. grauen Hintergrund im Formular "Meine Kontaktdaten bearbeiten" ist kein bischen lesbar. Bitte eine lesefreundliche Farbe für die Schrift wählen! Sonst scheitert die Anwender:in bereits beim Versuch, herauszufinden, was einzugeben wird.

**Comment by jw23578** [comment]
Die Farben wurden zwischenzeitlich komplett überbeitet.
