### ISSUE TITLE
 Scrollen nach unten auf der Hilfe-Seite klappt nicht

### ISSUE THREAD

**Issue by HappyPony** [jw23578/IchBinDa#4]
und zwar klappt es auf der Hilfe-Seite mit dem Scrollen nach unten nicht. S Screenshot:

![Hilfe-IBD](https://user-images.githubusercontent.com/3226308/90217349-6770ca00-de01-11ea-9d03-ee446a38095f.jpg)

**Comment by jw23578** [comment]
Danke, korrigiert.
Update folgt
