### ISSUE TITLE
Defined Questions aren't showing up in the app.

### ISSUE THREAD

**Issue by thies23** [jw23578/IchBinDa#8]
The defined questions aren't shown in the app.

Expected behaviour:
1. Create QR Code
2. Scan QR Code
3. Accept defined questions
4. Happy

Steps to reproduce:
1. Create QR Code with extra questions
2. Scan QR Code
3. Just enter bogus data to test
4. No questions asked
5. Custom Links and logo aren't shown either

Tested on Android 11 with the stable Play Store build.
Also verified on iOS 14.6

**Comment by jw23578** [comment]
Hi td00,
vielen Dank für deinen Test.
Nicht alle Daten landen im QR-Code, weil der dann zu komplex wird und nicht mehr ordentlich gescannt werden kann.
Deswegen werden die Extra-Fragen und auch der Link zum Logo (und alle anderen Links) in einer extra-Datei auf app-ichbinda.de gespeichert, die dann nachgeladen wird, wenn der entsprechende QR-Code gescannt wird.

Da auf dem Server zwischenzeitlich das SSL-Zertifikat ungültig war konnten diese Daten nicht mehr hochgeladen werden.
Jetzt werden die Zertifikate regelmäßig erneuert, bzw. das Serverprogramm neu gestartet, so dass die Zertifikate immer gültig sind.

Mit einem frisch angelegten QR-Code werden dann auch die Zusatzfragen korrekt abgefragt.

Grüße
Jens
